#   ---Plugin by niklas1623---
#
#   Copyright © 2020 niklas1623. Alle Rechte vorbehalten.
#
#   Nutze %player% für den Spielernamen
#

Settings:
  Prefix: '&8&l[&e&lDaily&b&lReward&8&l]'
  RewardCommand: 'procosmetics give coins %player% 100'

Messages:
  DailyReward:
    Send: true
    Msg: "%prefix% &7Du hast deine tägliche Belohnung erhalten!"
  NoPerm: "%prefix% &cDazu hast du keine Rechte!"
  UUIDofPlayer: "%prefix% &7Der Spieler &e%player% &7hat folgende UUID: &e%uuid%"
  HowToPInfo: "%prefix% &7Nutze /playerinfo <playername>"

#Die Zahlen sind die Tage ín folge!
Rewards:
  7:
    Cmd: "procosmetics give treasure %player% normal 1"
    Msg: "%prefix% &7Du hat eine &eNormale &7Treasure Chest erhalten!"
  14:
    Cmd: "say %player% ist 14 Tage in folge gejoint!"

#Bitte stelle hier deine Datenbank ein!
Database:
  username: username
  password: passwort
  database: DailyReward
  host: localhost
  port: '3306'
  options: "?autoReconnect=true&useSSL=false&AllowPublicKeyRetrieval=true&verifyServerCertificate=true"


